# Enable flake8-bugbear (`B`) rules
select = ["E" , "F", "B"]

# Never enforce `E501` (line length violations).
ignore = ["E501"]

# Avoid trying to fix flake8-bugbear  (`B`) violations
unfixable = ["B"]


# Ignore `E402` (import violations) in all `__init__.py` files,
[per-file-ignores]
"__init__.py" = ["E402"]
"path/to/file.py" = ["E402"]


[tool.ruff.isort]
multi_line_output = "VERTICAL_HANGING_INDENT"
force_grid_wrap = 2
line_length = 99
profile = "black" 